[package]
name = "mbr-rs"
version = "0.1.0"
authors = ["Roberto Guill√©n"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mbr-rs-macros = { path = "macros" }